#!/usr/bin/env bash

set -e

"${IDF_PATH}/components/esptool_py/esptool/esptool.py" \
     --chip esp8266 \
     elf2image \
     -o build/esp-app.bin \
     --version 3 \
     target/xtensa-esp8266-none-elf/release/esp-app

echo "You can now flash 'build/esp-app.bin'"
